package MTG.Cards.CardTypes;

public enum Types { INSTANT, SORCERY, LAND, CREATURE, TRIBAL, ARTIFACT,
    ENCHANTMENT, VANGUARD, PLANESWALKER, SCHEME, PLANE, CONSPIRACY,
    PHENOMENON, EATURECRAY, ENCHANT, PLAYER, UNKNOWN_TYPE }